### ISSUE TITLE
見出しの文字の大きさを変更する

### ISSUE THREAD

**Issue by takuya1150197** [toda2023-009/iniad-fake-homepage#2]
現状スケジュール内の内容の見出しよりも時間の表示の方が大きい等、文字の大きさの使い方がよろしくない箇所が多数ある。
見出しと時間等の内容で文字の大きさにメリハリをつけて、見やすい体裁を整える方が良いと思います。

**Comment by toda2023-009** [comment]
お疲れ様です。見出しの文字に加えて全体の文字サイズ及び文字色の修正をお願いできますでしょうか。

**Comment by takuya1150197** [comment]
お疲れ様です。
全体の文字サイズ及び文字サイズの修正の件、承知いたしました。
私の方で実施いたします。

**Comment by takuya1150197** [comment]
完了しました。

**Comment by toda2023-009** [comment]
確認しました。
