### ISSUE TITLE
文字サイズの調整

### ISSUE THREAD

**Issue by toda2023-009** [toda2023-009/iniad-fake-homepage#4]
タイトルやスケジュール内の時間など、文字サイズが一部そぐわない。
大きさが不適な文字はサイズを調整する。

**Comment by toda2023-009** [comment]
お疲れ様です。全体の文字サイズ及び文字色の修正をお願いできますでしょうか。

**Comment by takuya1150197** [comment]
お疲れ様です。
全体の文字サイズ及び文字サイズの修正の件、承知いたしました。
私の方で実施いたします。

**Comment by takuya1150197** [comment]
完了しました。

**Comment by toda2023-009** [comment]
確認しました。
