### ISSUE TITLE
文字の色使いを修正する。

### ISSUE THREAD

**Issue by takuya1150197** [toda2023-009/iniad-fake-homepage#6]
現在使用している、文字色はピンクや黄緑が多く、見ずらい状況であるので、黒色や青色等、修正後の背景に合う色を使用する。

**Comment by toda2023-009** [comment]
お疲れ様です。全体の文字サイズ及び文字色の修正をお願いできますでしょうか。

**Comment by takuya1150197** [comment]
お疲れ様です。
全体の文字サイズ及び文字サイズの修正の件、承知いたしました。
私の方で実施いたします。

**Comment by takuya1150197** [comment]
完了しました。

**Comment by toda2023-009** [comment]
確認しました。
