### ISSUE TITLE
レイアウト修正(枠で囲む)

### ISSUE THREAD

**Issue by takuya1150197** [toda2023-009/iniad-fake-homepage#8]
スケジュール　「学びを知ろう」・「入試を知ろう」の各時間割を枠で囲むことで、視覚的に見やすくする。

**Comment by toda2023-009** [comment]
お疲れ様です。レイアウトの修正をお願いできますでしょうか。

**Comment by takuya1150197** [comment]
お疲れ様です。
レイアウト変更については、晃さんも実施されるようですが、
2人の共同作業という形でよろしいでしょうか？
私は、枠で囲む部分のみ対応すればよろしいでしょうか？
ご指示いただければ幸いです。
宜しくお願い致します。

**Comment by toda2023-009** [comment]
お疲れ様です。
青島さんのイメージを知りたいこともありまして、
すみませんが、枠追加作業だけお願いします。

よろしくお願いします。

**Comment by takuya1150197** [comment]
承知いたしました。
実行します。

**Comment by takuya1150197** [comment]
完了しました。
枠を入れるべきかどうかは、次の講義の際にメンバーで検討できますと幸いです。
よろしくお願い致します。

**Comment by toda2023-009** [comment]
確認しました。
